export const theme = {
    // white: {
      backgroundColor: "#344966",
      colorText: "var(--dark, #0D1821)",
      colorBlack: "#000000",
      colorTextInput: "var(--dark blue, #344966)",
      colorTextButton: "white",
      colorTextInfo: "#4211c3",
      colorTextTitle: "#344966",
      backgroundColorStepper: "#F0F4EF",
      borderButton: "1px solid var(--dark, #0d1821)",
      prefixInputColor: "#b9bac3",
      // },
    // black: {
    //   colorPrimary: "#33f3c1",
    //   colorSecondary: "red",
    //   backgroundColor: "black",
    //   colorText: "#14056d",
    //   colorTextPost: "#eee3fb",
    //   colorTextInfo: "#b376ef",
    //   colorTextPlaceHolder: "#eee3fb",
    //   backgroundColorPosts: "#0f120e",
    //   backgroundColorPost: "#1a1d1a",
    //   backgroundImg: "img/night.jpg",
    //   borderPosts: "2px solid #b478f9",
    //   borderPost: "1px solid #b478f9",
    // },
  };
