export const theme = {
    white: {
      colorPrimary: "#344966",
      colorSecondary: "green",
      backgroundColor: "#344966",
      colorText: "#eee3fb",
      colorTextPost: "#14056d",
      colorTextInfo: "#4211c3",
      colorTextPlaceHolder: "#cfacf5",
      backgroundColorPosts: "#fcfffc",
      backgroundColorPost: "#fcfffc",
      backgroundImg: "img/snow_texture155.jpg",
      borderPosts: "2px solid #eee3fb",
      borderPost: "1px solid #cfacf5",
    },
    // black: {
    //   colorPrimary: "#33f3c1",
    //   colorSecondary: "red",
    //   backgroundColor: "black",
    //   colorText: "#14056d",
    //   colorTextPost: "#eee3fb",
    //   colorTextInfo: "#b376ef",
    //   colorTextPlaceHolder: "#eee3fb",
    //   backgroundColorPosts: "#0f120e",
    //   backgroundColorPost: "#1a1d1a",
    //   backgroundImg: "img/night.jpg",
    //   borderPosts: "2px solid #b478f9",
    //   borderPost: "1px solid #b478f9",
    // },
  };
